language: node_js
node_js: node
script: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "g4JqBFWh4dHSjShEGn2REL8tlbgJIfVMfC2uuJXCPHzWIdrRUrCKDh38gDBoVkHa2+Ahw4w7LOo6T+uACOPvM2FzAD32dkRoKVMaZZaK+8g51IVZVGu977xt4xrjU3RQPH0NIJHJnp5UvBrgtYT1ht6n4XlQ/e5uN/rS9mGie8b2HvlCdKExKn8zEvRklIcrB/jmWjA5oXAzBe493adFdDuXZboCvFh2hbAAxKk7cXNbj2vESWiqXu5bK2RnvxMG3IEpiIxZwx5dZzg9lTVzfxAh7K5H32eFEepOizVBcye9OH4L1MPFt5Fim1YafZJNcWbsE8GCEuxPZONh7nVZZWlXvsQNV8x/eO6M3u0BQBMB1SGaNZkaQOPH9pcwDd701XZPXjJE/OErB2sMhIouDHePB8psLQnaSsyRbahTHiyIbOoI+oIKQqsQ8uTH51SWS1cfodVWzMgMyK5LnorTEIL4z/qsk/S5y1UCOVH2ADkas2G/GFZQeB3hyt2V/b4MYwCv0IHdCbHlUfSvLdnhJwc38Q7+eWSxiyg2mHUNnYvFKvzGD2Vg3xDEk3+MlSFwrv8/uTNGSzmHIy7oVUUfR8B9ZSDAu0/baZgZxqbux/Chai3eu3jU+/s1y36WiiIxxW0VQC3t3GmyUE36AORD1zHCbN80ZskQF+2OhWV0l6A="
